apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
    - name: test
      image: vish/stress
      resources:
        limits:
          cpu: "200m"
        requests:
          cpu: "200m"
      args:
        - -cpus
        - "1"